#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc... root@rancher
rancher:
  docker:
    engine: docker-1.12.6
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      docker run -d --restart=unless-stopped -p 8080:8080 rancher/server